#!/bin/bash

full_date_tz=$(cat /etc/timezone)
if [[ "$2" == "pst" ]] || [[ "$2" == "PST" ]] || [[ "$2" == "pdt" ]] || [[ "$2" == "PDT" ]]; then
  full_date_tz='America/Los_Angeles'
fi

if [[ "$2" == "est" ]] || [[ "$2" == "EST" ]] || [[ "$2" == "edt" ]] || [[ "$2" == "EDT" ]]; then
  full_date_tz='America/New_York'
fi

if [[ "$2" == "cet" ]] || [[ "$2" == "CET" ]] || [[ "$2" == "cest" ]] || [[ "$2" == "CEST" ]]; then
  full_date_tz='Europe/Brussels'
fi

if [[ "$2" == "ist" ]] || [[ "$2" == "IST" ]]; then
  full_date_tz='Asia/Kolkata'
fi

if [[ $1 ]]; then
  full_date=$(TZ="$full_date_tz" date +%F)
  date -u '+%a %d %b %Y %T %Z' --date=@$(TZ="$full_date_tz" date "+%s" --date="$full_date $1")
  TZ='Europe/Brussels' date '+%a %d %b %Y %r %Z' --date=@$(TZ="$full_date_tz" date "+%s" --date="$full_date $1")
  TZ='America/New_York' date '+%a %d %b %Y %r %Z' --date=@$(TZ="$full_date_tz" date "+%s" --date="$full_date $1")
  TZ='America/Los_Angeles' date '+%a %d %b %Y %r %Z' --date=@$(TZ="$full_date_tz" date "+%s" --date="$full_date $1")
  TZ='Asia/Kolkata' date '+%a %d %b %Y %r %Z' --date=@$(TZ="$full_date_tz" date "+%s" --date="$full_date $1")
else
  date --utc '+%a %d %b %Y %T %Z'
fi
