#!/bin/bash

if [[ $1 ]]; then
  full_date=$(TZ='Asia/Kolkata' date +%F)
  TZ='Asia/Kolkata' date -u '+%a %d %b %Y %T %Z' --date=@$(TZ='Asia/Kolkata' date "+%s" --date="$full_date $1")
  TZ='America/New_York' date '+%a %d %b %Y %r %Z' --date=@$(TZ='Asia/Kolkata' date "+%s" --date="$full_date $1")
  TZ='America/Los_Angeles' date '+%a %d %b %Y %r %Z' --date=@$(TZ='Asia/Kolkata' date "+%s" --date="$full_date $1")
  TZ='Asia/Kolkata' date '+%a %d %b %Y %r %Z' --date=@$(TZ='Asia/Kolkata' date "+%s" --date="$full_date $1")
else
  date --utc '+%a %d %b %Y %T %Z'
fi
